---
# for targetCount == 3 in the test: only three options available in the list.
# it's excluded from options list if the value set to 'false'.
options:
  caller: true
  development: true
  fields:
    a: serviceA
    b: 123
